### ISSUE TITLE
Python 3.10 incompatibility - removed loop param in asyncio.open_connection

### ISSUE THREAD

**Issue by JanSimek** [c-soft/satel_integra#19]
* Satel Integra version: INTEGRA 128
* Python version: 3.10.1
* Operating System: Arch Linux x86_64

### Description

I configured the connection to Satel ETHM-1 Plus according to the [official documentation](https://www.home-assistant.io/integrations/satel_integra) but after restarting home assistant I can see the following error in logs:

```
Jan 29 19:51:56 simserver hass[679839]: 2022-01-29 19:51:56 WARNING (MainThread) [satel_integra.satel_integra] Exception during connecting: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'.
Jan 29 19:51:56 simserver hass[679839]: 2022-01-29 19:51:56 ERROR (MainThread) [homeassistant.setup] Setup failed for satel_integra: Integration failed to initialize.
```

### What I Did

My configuration looks like this:

```yaml
satel_integra:
  host: 192.168.1.112
  port: 7090
  partitions:
    01:
      name: "Domov"
  zones:
    01:
      name: "LAG Pradelna"
      type: "opening"
```
